services:
  frontend:
    image: frontend
    container_name: studygroup_1_pet_clinic_frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:3000'
    tty: true
    #networks:
    #  - COMMON_NETWORK